services:
  ts-portainer:
    image: tailscale/tailscale:latest
    container_name: ts-portainer
    hostname: portainer
    environment:
      - TS_AUTHKEY=
      - TS_SERVE_CONFIG=./ts-config/serve.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:internet 
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/ts-config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    network_mode: service:ts-portainer
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /portainer_data:/data portainer/portainer-ce
    
